# Utiliser l'image officielle OpenJDK comme étape d'exécution
FROM openjdk:17-jdk-alpine

# Définir le répertoire de travail à /app dans le conteneur
WORKDIR /app

# Copier le fichier JAR exécutable de l'étape de construction à l'étape d'exécution
# '/app/target/ams_data-0.0.1-SNAPSHOT.jar' est le fichier JAR généré par Maven
COPY ams-0.0.1-SNAPSHOT.jar .

# Exposer le port sur lequel l'application sera à l'écoute
# '8081' est le port typique pour les applications web
EXPOSE 8081

# Définir la commande pour exécuter l'application
# 'java -jar' est utilisé pour lancer l'application JAR
CMD ["java", "-jar", "ams-0.0.1-SNAPSHOT.jar"]