# Docker Compose
version: '3.3'

# Define services
services:
  # spring service
  spring:
    image: amsbackend2025:v3
    ports:
      - "8081:8081"
    container_name: spring_cont
    depends_on:
      - database
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/dbams2025?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sip
      SPRING_DATASOURCE_PASSWORD: sip-ac2025
    networks:
      - spr_net
  # Frontend Service 
  ams_front:
    image: amsfrontend2025:v2
    container_name: ams_frontend_cont
    ports:
      - "8070:80" 
    restart: always
    depends_on:
      - spring
    networks:
      - spr_net
  # Database Service (Mysql)
  database:
    image: mysql:latest
    container_name: mysql_cont
    volumes:
      - db_ams_vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: dbams2025
      MYSQL_USER: sip
      MYSQL_PASSWORD: sip-ac2025
      MYSQL_ROOT_PASSWORD: root
    networks:
      - spr_net

  # phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin
    container_name: pmadmin_cont
    depends_on:
      - database
    restart: always
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - spr_net

# Dec
volumes:
  db_ams_vol:

networks:
  spr_net:


